### ISSUE TITLE
SSH Tunneling doesn't work

### ISSUE THREAD

**Issue by ldub** [beekeeper-studio/beekeeper-studio#51]
When using a postgres database with an ssh tunnel, beekeeper shows that the database has no tables.

**Comment by rathboma** [comment]
interesting. Let me investigate.

**Comment by XzAeRo** [comment]
I just tried with a MariaDB server and happens the same. After switching between several databases, they tables did show up... Maybe a loading/latency issue?

**Comment by bradennapier** [comment]
I can't even get tunneling to work at all?  Just says it cant connect.  Same config works flawless for SequelPro and SQLPro

**Comment by pdepip** [comment]
If I had to guess, I'd say a lot of these issues are stemming from things like not supporting jump hosts, which could be resolved by taking the users ssh config file into consideration?

**Comment by ssuess** [comment]
Same issue here, trying to connect to MySQL. It connects (always on SECOND try btw, not first) and then shows no tables or dbs

**Comment by rathboma** [comment]
Yeah the tunneling code is a little flaky right now. Running queries through the tunnel isn't great.

I haven't spent much time on that code, but I'm prioritizing the connection bugs.

**Comment by hxhlb** [comment]
me too. @ssuess

**Comment by dufferzafar** [comment]
For me, the error is `(SSH) Channel open failure: Connection refused` while I'm able to connect using DBeaver just fine.

**Comment by rathboma** [comment]
My next milestone is to revamp the SSH and SSL libraries. Sorry this isn't working right :-(

**Comment by rathboma** [comment]
Can you all test this build? https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/106301681

You should be able to download the assets for your OS and install as usual

**Comment by ssuess** [comment]
This build seems to fix my connection and db listing problems. Thanks!

**Comment by chrisdlangton** [comment]
Using MySQL getting;

```
Error while signing data with privateKey: error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR
```
Works flawlessly without SSH tunnel. Also I can SSH fine outside beekeeper (including mysql-workbench)

**Comment by rathboma** [comment]
What platform, key type are you using?

Eg windows, pem

**Comment by chrisdlangton** [comment]
considering pem (a public key format) is never going to work... I am using a private key generated via defaults of `ssh-keygen` RSA2048SHA256

Ubuntu 20.04 `uname -a`;
```
Linux alteran 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
Installed clean from [instructions](https://docs.beekeeperstudio.io/installation/#linux-installation) after the issue #40 I raised with snap and you closed as being due to a snap restriction and i solved it by not using snap, so not really resolving the issue but closed anyway..

My conclusion is Beekeeper for Linux is a toy/alpha tool used for localhost and not ready for enterprise/production use - maybe other platforms, perhaps more familiar to the devs, work in real world scenarios.

**Comment by rathboma** [comment]
Hey @chrisdlangton,

So sorry you're frustrated with the app :-(. 

Beekeeper Studio is definitely early -- we only announce it on April 20th. SSH tunneling is something we adapted from an earlier library, and yes it is the most broken part of the product right now. I have some servers that I use for testing SSH, but not all combos of dbs and configs are covered. It's a bit of a cat and mouse game.

I'm trying to determine what folks are trying to use for their SSH connection configs. For example - private keys generated from putty have been causing issues, and because I don't have docs for SSH tunnels yet I've had to field several informal questions about private/public keys, hence me dropping PEM as a suggestion :-).

Follow up Questions

- What version of MySQL are you using? (8?)
- Are you also enabling SSL for your connection?
- When you are tunneling, are you keeping the hostname the same, or changing it to locahost? eg:
```
host: localhost, port: 3306
sshhost: myserver.com

# OR:
host: myserver.com, port; 3306
sshhost: myserver.com

```
Thanks for your help

**Comment by chrisdlangton** [comment]
@rathboma 
Didn't mean the critical feedback to appear as frustration, text is.. not the best.

To give the project benefit of doubt the key pair was generated fresh, and the public key was added to authorized_keys of a digital ocean docker droplet. My production use case is EC2 Amazon Linux 2 (centos) as a temporary/breakglass bastion to access RDS/Aurora.

I tried various databases so versions, but the isolated test on the droplet was a container  image `mysql:5.7@sha256:ba2eda1bf1249bd7e7160fa6c446d03b3261f75d3de91bc2125967d39db1525c` specifically docker-compose.yaml;

```yaml
version: '3.6'
x-defaults: &defaults
  restart: unless-stopped
  logging:
    options:
      max-size: "10m"
      max-file: "3"

  mysql:
    <<: *defaults
    image: mysql:5.7@sha256:ba2eda1bf1249bd7e7160fa6c446d03b3261f75d3de91bc2125967d39db1525c
    container_name: mysql
    volumes:
      - /mnt/volume_sgp1_02/mysql_data:/var/lib/mysql
    command: '--max_allowed_packet=65011712 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=1024 --skip-show-database --skip-grant-tables'
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
```
and the tunnel uses ssh config for simplicity;

```
Host do-docker
  HostName www.example.com
  User root
  IdentityFile /home/<user>/.ssh/id_rsa
  Compression yes
  ConnectionAttempts 3
  ConnectTimeout 5
  IdentitiesOnly yes
```

Replace host and user. Not using SSL for the isolated test (yet), but RDS/Aurora does.

The mysql IP address is usually a `172.` in docker, you can find it via `docker inspect <image name>` for this isolated test, but with RDS/Aurora you use a DNS record in the tunnel connection configuration not an IP
